export function getFileExtension(filename: string): string {
  const ext = filename.split(".").pop()?.toLowerCase();
  const extensionMap: { [key: string]: string } = {
    js: "javascript",
    ts: "typescript",
    jsx: "javascript",
    tsx: "typescript",
    py: "python",
    java: "java",
    cpp: "cpp",
    c: "c",
    cs: "csharp",
    php: "php",
    rb: "ruby",
    go: "go",
    rs: "rust",
    swift: "swift",
    kt: "kotlin",
    html: "html",
    css: "css",
    scss: "scss",
    sass: "sass",
    less: "less",
    json: "json",
    xml: "xml",
    yaml: "yaml",
    yml: "yaml",
    md: "markdown",
    sql: "sql",
    sh: "bash",
    bash: "bash",
    zsh: "zsh",
    fish: "fish",
    vue: "vue",
    svelte: "svelte",
    wxml: "xml",
    wxss: "css",
    wxs: "javascript",
  };
  return extensionMap[ext || ""] || "text";
}
